export * from './Hero'
export * from './Navbar'
export * from './Feactures'
export * from './Gallery'
export * from './ImageSlider'
export * from './Contact'
export * from './Footer'
export * from './Gallery3.jsx'